import { app } from 'electron';
import fs from 'fs';
import path from 'path';
import { EventEmitter } from 'events';

export interface GraftConfig {
    // URL for the Graft MetaStore
    metastore: string;
    // URL for the Graft PageStore
    pagestore: string;
    // API token for MetaStore and PageStore (optional)
    token?: string;
    // Enable/disable background synchronization
    autosync: boolean;
    // Unique Client ID (optional, auto-generated if not set)
    clientId?: string;
}

export interface AppConfig {
    // the folder where the data is stored
    dataFolder: string;
    // the api agent config
    apiAgentConfig: {
        url: string;
        enabled: boolean;
    };
    // Security configuration
    security: {
        webSecurity: boolean;
    };
    // Sync configuration
    sync: {
        graft: GraftConfig;
        // Future sync-related settings can go here
    };
}

const emptyConfig: AppConfig = {
    dataFolder: '', // Will likely be set based on userData path or similar
    apiAgentConfig: {
        url: '',
        enabled: false,
    },
    security: {
        webSecurity: true,
    },
    sync: { // Updated structure
        graft: {
            metastore: 'http://127.0.0.1:3001', // Default from docs
            pagestore: 'http://127.0.0.1:3000', // Default from docs
            token: undefined, // No default token
            autosync: true, // Default from docs
            clientId: undefined, // Will be auto-generated by graft if not set
        },
    }
};

export class ConfigManager extends EventEmitter {
    private configPath: string;
    private config: AppConfig;

    constructor(configPath: string) {
        super();
        this.configPath = configPath;
        this.config = this.loadConfig();
        // Ensure existing configs have the new graft structure within sync
        this.ensureDefaultSyncGraftConfig();
    }

    private loadConfig(): AppConfig {
        let loadedConfig = JSON.parse(JSON.stringify(emptyConfig)); // Deep clone defaults
        if (fs.existsSync(this.configPath)) {
            try {
                const rawData = fs.readFileSync(this.configPath, 'utf-8');
                const parsedData = JSON.parse(rawData);

                // Simple migration: If old top-level 'graft' exists and 'sync' doesn't, move it.
                if (parsedData.graft && !parsedData.sync) {
                    console.warn("Migrating top-level 'graft' config to 'sync.graft'.");
                    parsedData.sync = { graft: parsedData.graft };
                    delete parsedData.graft; // Remove old top-level key
                    // Consider triggering a save after migration? For now, rely on ensureDefaultSyncGraftConfig save.
                }

                // Deep merge ensuring 'sync' and 'sync.graft' exist
                loadedConfig = {
                    ...loadedConfig,
                    ...parsedData,
                    sync: {
                        ...(loadedConfig.sync || {}), // Ensure sync object exists
                        ...(parsedData.sync || {}),   // Overlay saved sync settings
                        graft: {
                            ...(loadedConfig.sync.graft),        // Start with defaults for graft
                            ...((parsedData.sync && parsedData.sync.graft) || {}), // Overlay saved graft settings
                        },
                    },
                };
            } catch (error) {
                console.error("Error loading or parsing config file:", this.configPath, error);
                // Fallback to deep clone of default config if loading/parsing fails
                loadedConfig = JSON.parse(JSON.stringify(emptyConfig));
            }
        }
        return loadedConfig;
    }

    // Ensure that the loaded config has the sync.graft structure, applying defaults if missing
    private ensureDefaultSyncGraftConfig(): void {
        let needsSave = false;
        // Ensure sync object exists
        if (typeof this.config.sync !== 'object' || this.config.sync === null) {
            console.warn("Sync config section missing, initializing with defaults.");
            this.config.sync = JSON.parse(JSON.stringify(emptyConfig.sync)); // Deep clone default sync
            needsSave = true;
        }
        // Ensure sync.graft object exists
        if (typeof this.config.sync.graft !== 'object' || this.config.sync.graft === null) {
            console.warn("Sync.graft config section missing, initializing with defaults.");
            this.config.sync.graft = { ...emptyConfig.sync.graft };
            needsSave = true;
        } else {
            // Check individual keys within sync.graft and apply defaults if missing
            for (const key of Object.keys(emptyConfig.sync.graft) as Array<keyof GraftConfig>) {
                if (!(key in this.config.sync.graft)) {
                    console.warn(`Sync.graft config key '${key}' missing, applying default.`);
                    (this.config.sync.graft as any)[key] = emptyConfig.sync.graft[key];
                    needsSave = true;
                }
            }
        }
        if (needsSave) {
            this.saveConfig();
        }
    }

    private saveConfig(): void {
        try {
            const rawData = JSON.stringify(this.config, null, 2);
            // Ensure directory exists before writing
            fs.mkdirSync(path.dirname(this.configPath), { recursive: true });
            fs.writeFileSync(this.configPath, rawData, 'utf-8');
        } catch (error) {
            console.error("Error saving config file:", this.configPath, error);
        }
    }

    // Type-safe getter for top-level keys
    public get<K extends keyof AppConfig>(key: K): AppConfig[K] {
        return this.config[key];
    }

    // Type-safe setter for top-level keys
    public set<K extends keyof AppConfig>(key: K, value: AppConfig[K]): void {
        const oldValue = this.config[key];
        if (JSON.stringify(oldValue) !== JSON.stringify(value)) { // Avoid saving if no change
            this.config[key] = value;
            this.saveConfig();
            console.log('Config changed:', { key, oldValue, newValue: value });
            this.emit('configChanged', { key, oldValue, newValue: value });
        }
    }

    // Getter for graft settings
    public getGraftConfig(): GraftConfig {
        // Return a copy to prevent direct modification
        // Ensure sync and graft exist before accessing, falling back to defaults if necessary
        const graftConfig = this.config.sync?.graft;
        return { ...(graftConfig || emptyConfig.sync.graft) };
    }

    // Setter for graft settings (replaces the entire graft object or merges partial)
    public setGraftConfig(graftConfig: Partial<GraftConfig>): void {
        // Ensure sync object exists
        if (!this.config.sync) {
             this.config.sync = JSON.parse(JSON.stringify(emptyConfig.sync));
        }
        const oldGraftConfig = { ...(this.config.sync.graft || emptyConfig.sync.graft) };
        const newGraftConfig = { ...oldGraftConfig, ...graftConfig }; // Merge partial updates

        if (JSON.stringify(oldGraftConfig) !== JSON.stringify(newGraftConfig)) {
            this.config.sync.graft = newGraftConfig;
            this.saveConfig();
            console.log('Graft config changed (within sync):', { oldValue: oldGraftConfig, newValue: newGraftConfig });
            // Emit a specific event or use the generic one, adjusting payload structure
            this.emit('configChanged', { key: 'sync.graft', oldValue: oldGraftConfig, newValue: newGraftConfig });
        }
    }
}

let configManagerInstance: ConfigManager | null = null;

export function getConfigManager(): ConfigManager {
    if (!configManagerInstance) {
        const userDataPath = app.getPath('userData');
        const configFilePath = path.join(userDataPath, 'config.json');
        configManagerInstance = new ConfigManager(configFilePath);
    }
    return configManagerInstance;
}
